version: '2'
services:

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
     - "5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data

  # mongodb:
  #   image: mongo:4.4
  #   restart: always
  #   ports:
  #    - "27017"
  #   volumes:
  #    - mongodb_data:/data/db

  nginx:
    build: ./nginx
    restart: always
    ports:
     - "8080:80"

  roleman:
    build: ./roleman
    restart: always

  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mongodb_data:
  mysql_data:
